[project]
name = "curso2"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.6",
    "keras>=3.11.2",
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
    "scikit-learn>=1.7.1",
    "tensorflow>=2.20.0",
]
