[project]
name = "curso5"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "jupyterlab>=4.4.6",
    "keras>=3.11.3",
    "keras-cv>=0.9.0",
    "matplotlib>=3.10.6",
    "tensorflow>=2.20.0",
    "tqdm>=4.67.1",
]
